# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/result/Dockerfile'
        repository: result
  
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'ecr-aws-softtek'
        regionName: 'us-east-1'
        imageSource: 'imagename'
        sourceImageName: 'result'
        sourceImageTag: '$(Build.BuildId)'
        repositoryName: 'eaum1'
        pushTag: '$(Build.BuildId)'